import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const NunitoFont = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body className={`${NunitoFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
