import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import AuthProviders from "@/_providers/auth";
import FooterBar from "@/_components/footerbar";
import { Toaster } from "sonner";

const NunitoFont = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "BarberBoss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body className={`${NunitoFont.variable}`}>
        <AuthProviders>
          <div className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <FooterBar />
          </div>
        </AuthProviders>
        <Toaster />
      </body>
    </html>
  );
}
