import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import AuthProviders from "@/_providers/auth";

const NunitoFont = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "BarberBoss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body className={`${NunitoFont.variable} antialiased`}>
        <AuthProviders>
        {children}
        </AuthProviders>
        </body>
    </html>
  );
}
